#!/bin/bash

#PBS -l nodes=1:ppn=12
#PBS -l walltime=0:01:00

#PBS -q batch
#PBS -N Mandelbrot
#PBS -j oe

cd /home/arrowoode/class071819
mpiexec -np 1 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./mandelbrot.cx