#!/bin/bash

#PBS -l nodes=3:ppn=12
#PBS -l walltime=0:10:00

#PBS -q batch
#PBS -N PingPong
#PBS -j oe

cd /home/arrowoode/PA1
mpiexec -np 3 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./ping-pong.x