#!/bin/bash

#PBS -l nodes=6:ppn=12
#PBS -l walltime=0:05:00

#PBS -q batch
#PBS -N Integral
#PBS -j oe

cd /home/arrowoode/class070919
mpiexec -np 6 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./integral.x