#!/bin/bash

#PBS -l nodes=1:ppn=12
#PBS -l walltime=0:05:00

#PBS -q batch
#PBS -N Integral
#PBS -j oe

cd /home/arrowoode/LE1
mpiexec -np 1 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./integral.cx