#!/bin/bash

#PBS -l nodes=6:ppn=12
#PBS -l walltime=0:05:00

#PBS -q batch
#PBS -N HeatFTCS
#PBS -j oe

cd /home/arrowoode/LE1
mpiexec -np 6 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./heatFTCS.cx