#!/bin/bash

#PBS -l nodes=4:ppn=12
#PBS -l walltime=0:01:00

#PBS -q batch
#PBS -N 4R4TMandelbrot
#PBS -j oe

cd /home/arrowoode/PA3
export OMP_NUM_THREADS=4
mpiexec -np 4 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./mandelbrot.cx