#!/bin/bash

#PBS -l nodes=4:ppn=12
#PBS -l walltime=0:01:00

#PBS -q batch
#PBS -N LA3Parallel
#PBS -j oe

export COUNTER1=PAPI_L1_DCM
export COUNTER2=P_WALL_CLOCK_TIME

cd /home/arrowoode/LA3
mpiexec -np 4 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./LA3P.x
