#!/bin/bash

#PBS -l nodes=2:ppn=12
#PBS -l walltime=1:00:00

#PBS -q batch
#PBS -N MPIExample
#PBS -j oe

cd /home/arrowoode/class053019
mpiexec -np 2 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./ex.x