#!/bin/bash

#PBS -l nodes=4:ppn=12
#PBS -l walltime=1:00:00

#PBS -q batch
#PBS -N MPIExample2
#PBS -j oe

cd /home/arrowoode/class053019
mpiexec -np 4 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./ex2.x